/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AgriculturalAccountingRouteImport } from './routes/agricultural-accounting'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as OutsourceRouteImport } from './routes/outsource'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WhoWeHelpRouteImport } from './routes/who-we-help'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AgriculturalAccountingRoute = AgriculturalAccountingRouteImport.update({
  id: '/agricultural-accounting',
  path: '/agricultural-accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const OutsourceRoute = OutsourceRouteImport.update({
  id: '/outsource',
  path: '/outsource',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeHelpRoute = WhoWeHelpRouteImport.update({
  id: '/who-we-help',
  path: '/who-we-help',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/agricultural-accounting': typeof AgriculturalAccountingRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/outsource': typeof OutsourceRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/who-we-help': typeof WhoWeHelpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/agricultural-accounting': typeof AgriculturalAccountingRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/outsource': typeof OutsourceRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/who-we-help': typeof WhoWeHelpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/agricultural-accounting': typeof AgriculturalAccountingRoute
  '/approach': typeof ApproachRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/outsource': typeof OutsourceRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/who-we-help': typeof WhoWeHelpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/agricultural-accounting'
    | '/approach'
    | '/contact'
    | '/faq'
    | '/outsource'
    | '/pricing'
    | '/services'
    | '/who-we-help'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/agricultural-accounting'
    | '/approach'
    | '/contact'
    | '/faq'
    | '/outsource'
    | '/pricing'
    | '/services'
    | '/who-we-help'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/agricultural-accounting'
    | '/approach'
    | '/contact'
    | '/faq'
    | '/outsource'
    | '/pricing'
    | '/services'
    | '/who-we-help'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AgriculturalAccountingRoute: typeof AgriculturalAccountingRoute
  ApproachRoute: typeof ApproachRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  OutsourceRoute: typeof OutsourceRoute
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRoute
  WhoWeHelpRoute: typeof WhoWeHelpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agricultural-accounting': {
      id: '/agricultural-accounting'
      path: '/agricultural-accounting'
      fullPath: '/agricultural-accounting'
      preLoaderRoute: typeof AgriculturalAccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outsource': {
      id: '/outsource'
      path: '/outsource'
      fullPath: '/outsource'
      preLoaderRoute: typeof OutsourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-help': {
      id: '/who-we-help'
      path: '/who-we-help'
      fullPath: '/who-we-help'
      preLoaderRoute: typeof WhoWeHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AgriculturalAccountingRoute: AgriculturalAccountingRoute,
  ApproachRoute: ApproachRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  OutsourceRoute: OutsourceRoute,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRoute,
  WhoWeHelpRoute: WhoWeHelpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
